### ISSUE TITLE
Remove item in from the queue

### ISSUE THREAD

**Issue by radeklos** [thisissoon/FM-Frontend#101]
There is a new endpoint for [removing](https://github.com/thisissoon/FM-API#delete) items from the queue: 

`http DELETE http://localhost/player/queue/`
```json
{
  "uri": "spotify:track:6FshvOVICpRVkwpYE5BYTD",
  "uuid": "16fd2706-8baf-433b-82eb-8c7fada847da",
}
```

The view returns 200 when an item has been removed and 204 when an item cannot be found. Response doesn't have any data.

**Comment by bcmrbvm** [comment]
This I think will depend on #86 being implemented first

**Comment by bcmrbvm** [comment]
There seem to be a CORS Issue with the API thats blocking this. Also there may be an issue with passing data in a delete request.

**Comment by radeklos** [comment]
It should be fixed now.. can you please take a look?

**Comment by bcmrbvm** [comment]
thanks @radeklos will try again
