### ISSUE TITLE
View more tracks in playlist if more than 20

### ISSUE THREAD

**Issue by bcmrbvm** [thisissoon/FM-Frontend#128]

**Comment by jamesjwarren** [comment]
@bcmrbvm this could use similar paginating to the history view if we can fix #129

**Comment by bcmrbvm** [comment]
@jamesjwarren I was thinking just to put in a button for now and then once #129 is fixed to combine both so the button acts as a fallback if the infiniteScroll directive fails

**Comment by jamesjwarren** [comment]
@bcmrbvm sounds good :)
