### ISSUE TITLE
should playlist total time include the currently playing track?

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/FM-Frontend#131]

**Comment by jamesjwarren** [comment]
Difficult question! I didn't think so as the playlist by definition doesn't include the current track. If it was included the time should also count down as playback progresses...

@krak3n / @radeklos any opinions?

**Comment by radeklos** [comment]
I think that it shouldn't include current track.

**Comment by bcmrbvm** [comment]
To me it makes sense to include it as it gives a more accurate representation of when the music will finish playing. If for example an hour long track is playing but there is only 12 mins of music in the queue, to me it was very misleading

**Comment by radeklos** [comment]
True but then total time should be changed every second based on elapsed time of the current track.

**Comment by bcmrbvm** [comment]
maybe need to ask Fred or Ryan

**Comment by edwardoparearyee** [comment]
Ryan says no, so it's a no
