### ISSUE TITLE
Add ability to login to Spotify account

### ISSUE THREAD

**Issue by bcmrbvm** [thisissoon/FM-Frontend#147]
So a user can view they own playlists, we need to implement a feature to login to their Spotify account

**Comment by bcmrbvm** [comment]
@krak3n @radeklos I think this needs to be implemented in the API as the FE would expose any API keys required to do this.

**Comment by radeklos** [comment]
You should be able to connect to spotify using this endpoint: https://api.thisissoon.fm/oauth2/spotify/connect as spotify callback url. We have to create soon fm spotify app..

**Comment by bcmrbvm** [comment]
@radeklos that sounds perfect
