### ISSUE TITLE
Track timer oscillates between two positions

### ISSUE THREAD

**Issue by jamesjwarren** [thisissoon/FM-Frontend#191]
Occasionally the progress bar gets stuck in a scenario where it oscillates between two positions as it progresses.

**Comment by jamesjwarren** [comment]
Also there is still an issue with it getting stuck like this:
 
![screen shot 2015-12-16 at 11 09 05](https://cloud.githubusercontent.com/assets/1857944/11839425/7e653148-a3e5-11e5-869b-4b0074c1898f.png)

**Comment by edwardoparearyee** [comment]
@jamesjwarren regarding the second issue, I can replicate this if I pause a track twice so press: (**pause**, **play**, **pause**, **play**).

Regarding the first issue I think this sounds like there are two different instances of the track timer `$interval` running one with the pause issue applied and the other without.

I am looking into these now
