### ISSUE TITLE
Album art aspect ratio squashed in search

### ISSUE THREAD

**Issue by jamesjwarren** [thisissoon/FM-Frontend#27]
The aspect ratio of album artwork is sometimes squashed in search dropdown.

![screenshot 2015-03-18 11 34 16](https://cloud.githubusercontent.com/assets/1857944/6707840/dd6d0238-cd62-11e4-937a-9bebfab61f68.png)

**Comment by eopa** [comment]
@jamesjwarren i've already fixed this, i'm currently refactoring some of the markup and styling and fixed this as part of that.

**Comment by jamesjwarren** [comment]
@eopa nice one
