### ISSUE TITLE
Empty track in playlist when last track in playlist finishes

### ISSUE THREAD

**Issue by eopa** [thisissoon/FM-Frontend#39]
When the last track in playlist finishes, there is an empty track still left in the playlist, so instead of the "no tracks in playlist" message being displayed there is just an empty track directive with no data. 

If you refresh the page then the correct message is shown. But if your on the page when the last track finishes then an empt track is still left in the playlist array.

**Comment by jamesjwarren** [comment]
I think this is caused by the onEnd method checking for the `spotify_uri` which has now been updated to `uri`. https://github.com/thisissoon/FM-Frontend/blob/develop/app/js/fm-player/controllers/PlayerCtrl.js#L195

I'll submit a PR.

**Comment by eopa** [comment]
cool
