### ISSUE TITLE
Production SSL API

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-Frontend#42]
The production API will now live @ https://thisissoon.fm :smile:

**Comment by eopa** [comment]
SSL is currently still broken due to sockets still being `http`
![screen shot 2015-03-24 at 15 13 54](https://cloud.githubusercontent.com/assets/7836746/6804977/8de5c7ec-d238-11e4-8fb4-cdcc8e81c69a.png)

**Comment by krak3n** [comment]
The SSL is being generated currently, will let you know once its up.

**Comment by krak3n** [comment]
https://sockets.thisissoon.fm/ now works
