### ISSUE TITLE
Add stats feature

### ISSUE THREAD

**Issue by bcmrbvm** [thisissoon/FM-Frontend#72]

**Comment by krak3n** [comment]
We'll need to implement some API endpoints for this. I have the raw SQL queries for the basic ones. Let me know what else you need.

**Comment by jamesjwarren** [comment]
Would it be possible to do per user stats too? Eg:
- DJs favourite genres
- DJs favourite artist/track etc.

**Comment by krak3n** [comment]
Yup @jamesjwarren shove an issue in the API repo, one of us will get to it, or add it yourself if your feeling adventurous :wink:

**Comment by jamesjwarren** [comment]
Specific user stats are available at `https://api.thisissoon.fm/users/:userId/stats/` so can now be integrated into user profiles on the FE.
