### ISSUE TITLE
Volume slider should fill volume bar instead of being just a slider

### ISSUE THREAD

**Issue by eopa** [thisissoon/FM-Frontend#73]

**Comment by krak3n** [comment]
I'm gonna open an issue on the API to add min and max ranges to volume since anything below 50 and above 90 is un usable. This should make the slider more useful. You shouldn't need to change anything and still send values between 0/100.

**Comment by eopa** [comment]
@krak3n :+1:

**Comment by jamesjwarren** [comment]
only IE natively supports styling upper and lower segments of `input[type="range"]` but we could use a JS solution with a sharp gradient background similar to this: http://codepen.io/ryanttb/pen/fHyEJ
