### ISSUE TITLE
Feature: Track Progress Bar

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-Frontend#84]
Been having a think about how we can achieve this easily. 

The Player can now tick over the track every second and update a Redis key `fm:player:progress` to hold the `%` value we are through the track. This can be returned as part of the `/player/current` resource allowing you to place an element at the correct position of the progress bar. This will not update if the player is in a paused state.

When you get the `play` event you can start your progress bar. How fast the bar moves will need to be calculated based on the duration of the track, so the bar should move slower for a 5min track vs a 3min track. When you get a `pause` event you can stop the progress bar. When you get a `resume` event you can start the bar off again.

This should give us everything we need to display track progress.

In the future we can also support Seeking, this will mean a new event, probably called `seek_to` and just send a `%` value to seek to in the track, like `23%`.

Should work?

**Comment by jamesjwarren** [comment]
Awesome :smile: sounds like everything we would need.

**Comment by eopa** [comment]
cool stuff!

**Comment by krak3n** [comment]
This has been implemented in the player here thisisoon/FM-SoundWave#4

See thisissoon/FM-API/#4 for the API Implementation.

Once these issues are closed we will be ready to rock on the FE.

**Comment by krak3n** [comment]
This is now deployed. Both player and api will track the current elapsed time (not percentage) of the track.

You can use:

``` json
{
  "player":{  
    "elapsed_time":65000
  }
}
```

To calculate the percentage complete vs the tracks duration. 

Example `/player/current` JSON:

``` json
{  
  "track":{  
    "album":{  
      "id":"2b69e505-beff-480f-94a3-542a7761e8dc",
      "images":[  
        {  
          "url":"https://i.scdn.co/image/e032eee1c0bdc8970bf34ccf7f30ef600a5ef7c0",
          "width":640,
          "height":573
        },
        {  
          "url":"https://i.scdn.co/image/d43f2be852e0b369b3ef50d82b59269dcc5eba2b",
          "width":300,
          "height":269
        },
        {  
          "url":"https://i.scdn.co/image/f55ffe7039a4bb177563b47f216210d1cc68b2e1",
          "width":64,
          "height":57
        }
      ],
      "name":"Broken Bells",
      "uri":"spotify:album:0X7WyEKdm5afGj1fmD7Blx"
    },
    "name":"The Ghost Inside",
    "uri":"spotify:track:32fmQsWSAaDas2MJRyMSGG",
    "play_count":1,
    "artists":[  
      {  
        "id":"6a280deb-b809-4a3c-9582-a5f01328e669",
        "uri":"spotify:artist:6dgwEwnK0YtDfS9XhRwBTG",
        "name":"Broken Bells"
      }
    ],
    "duration":198040,
    "id":"a5720516-0a10-4c5a-836d-c3ae9cf4e4a1"
  },
  "player":{  
    "elapsed_time":65000
  },
  "user":{  
    "family_name":"Holmes",
    "display_name":"Florence Holmes",
    "avatar_url":"https://lh3.googleusercontent.com/-zijJ8z7XR-8/AAAAAAAAAAI/AAAAAAAAACk/WPtByWe1SlU/photo.jpg",
    "spotify_playlists":null,
    "given_name":"Florence",
    "id":"5db00514-2628-4017-99c1-01ffc601e696"
  }
}
```

**Comment by jamesjwarren** [comment]
:+1: looks good
