### ISSUE TITLE
Feature: Track Context Menu

### ISSUE THREAD

**Issue by jamesjwarren** [thisissoon/FM-Frontend#86]
Having a track context menu would offer a neat space to add track specific features, for example 'Add to playlist` from history view (I'm sure there could be other actions in the future).

Some libraries that might offer a solution:
https://github.com/ianwalter/ng-context-menu
https://github.com/Templarian/ui.bootstrap.contextMenu

**Comment by bcmrbvm** [comment]
@jamesjwarren i agree we need a context menu, don't think we need a library to do this, this is simple enough I think to do in the track directive using bootstrap.
