### ISSUE TITLE
History pagination is still not working correctly

### ISSUE THREAD

**Issue by bcmrbvm** [thisissoon/FM-Frontend#95]
It still only loads up to page 2. If this is becoming an issue maybe consider using just a simple button to load the next page of results.

**Comment by bcmrbvm** [comment]
@jamesjwarren thinking about this maybe you should also write end to end tests for this to test it a browser. Maybe that will help get to the cause of the issue

**Comment by jamesjwarren** [comment]
@bcmrbvm good idea. I think it must still be to do with the pagination meta not getting read properly, as whenever I try it locally with mocked data in the controller it works ok. I'll try the e2e tests.

**Comment by jamesjwarren** [comment]
@bcmrbvm investigated this further, turned out to be caused by CORS not exposing the custom headers. It will be fixed in https://github.com/thisissoon/FM-API/pull/41

**Comment by bcmrbvm** [comment]
cool
