### ISSUE TITLE
Total played seconds

### ISSUE THREAD

**Issue by radeklos** [thisissoon/FM-Frontend#98]
It seems that total played seconds are not correct and it looks like math issue.. I was on time 2:00 and when I hit refresh I got 1:40 what was returned by api that time.

**Comment by jamesjwarren** [comment]
This may be to do with an API issue I was experiencing yesterday, where the API sometimes returns the wrong elapsed time on calling player/current on the play event. Sometimes it still has the elapsed time from the previous track, which means the FE starts from that time for the next track.

**Comment by krak3n** [comment]
Will look at the Player, if its missing ticks or updating redis is failing we may have to look at another method for telling the player how far through a track we are.

**Comment by krak3n** [comment]
We have now fixed this API and Player side so we shouldn't have any weird time drifts now.
