### ISSUE TITLE
Pause / Resume Progress Reset

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-Frontend#99]
The Progress bar appears to reset when resuming from a pause state.

Here is a handy gif :stuck_out_tongue: 

![](http://g.recordit.co/kAUxlovajo.gif)

**Comment by radeklos** [comment]
Is it feature or bug? :)

**Comment by krak3n** [comment]
lol bug :stuck_out_tongue:

**Comment by jamesjwarren** [comment]
Definite bug, will look into it when I get a chance.
